<img src="https://github.com/christopherhuntley/BUAN6510/blob/master/img/Dolan.png?raw=true" width="180px" align="right">

# **BUAN 6510**
# **Homework 9: A Decade of Laundry Tags** 
_Building a Data Warehouse from Source Data._


In this assignment you will build a modestly-sized data warehouse from a single denormalized CSV file and static data. The large CSV file contains data from 90K garment tags scanned by a dry cleaning chain in southeastern Connecticut. The static data comes from the IT staff at the company. 

This time you will have to provide all the ELT code yourself.

## **1. Study the ERD.**

![HW9 ERD](https://github.com/christopherhuntley/BUAN6510/raw/master/img/HW9_GarmentTags_DW.png)

## **2. Download the data to your Colab workspace.**

In [ ]:
# download the source data from GitHub to the /content 
!wget https://github.com/christopherhuntley/BUAN6510/raw/master/data/DeluxCare/HW9_garment_tags.csv
!wget https://raw.githubusercontent.com/christopherhuntley/BUAN6510/master/data/DeluxCare/HW9_ServiceTypes.csv

## **3. Create a new SQLite database and import the CSV files into import tables.**

- You will likely need to borrow and modify code from previous homeworks. 
- Name the database `HW9_GarmentTags.db`. Where to put it is up to you. 
- Name the tables for the garment tag data `GarmentTags_import` and the service type data `ServiceTypes_import`.

## **4. Write and debug SQL DDL for the tables in the ERD.** 
- Remember, we're using SQLite, not MySQL. Use the right data types. You may want to review SQLite types and keys again to be sure. 
- Name each table in the plural form, with lowercase letters and underscores.
- Name each column with lowercase letters and underscores. 
- Each PK should be autonumbered *except* `service_id`,  which should use `SMALLINT` data type to [avoid aliasing the `rowid` column](https://www.sqlitetutorial.net/sqlite-primary-key/).  
- You will need to create the tables in the right order; otherwise the FKs constraints won't work.
- Use `DROP TABLE IF EXISTS ...` statements to clear out each table before the `CREATE ...` statements.

## **5. Populate the service types dimension table.**
The data in the `ServiceTypes_import` table is pre-programmed into the point of sale system. The numbers correspond to the keys on the cash register.

## **6. Populate remaining tables from `GarmentTags_import`.**
- Remember that the order matters. 
- Where possible, use the numeric dimension identifier columns that already exist in the data rather than generating new keys values. 
- You will need to generate surrogate key values for `brand_id`. Since `brand_id` does not exist in the source data you will need to use an alternate key for the joins when populating the table.

## **7. Test with `SELECT` queries.**

**How many sales were made in each town?**

**Which town had the highest total sales in 2012?**

**Which 10 brands were the most common?**

**How many 'RALPH LAUREN' garments were cleaned in each year?**

**How popular was `RALPH LAUREN` in each town in 2012?**

## **Turn it in!**
Submit this Colab Norebook in Google Classroom.
If you want to keep a copy of the database file, then drag it to Google Drive (if it is not there already).